version: "3.8"
services:
  database:
    container_name: postgres
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_USER: user-development
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: goapi-development
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  gateway:
    container_name: gateway
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        project: gateway
        project_path: ./cmd
    ports:
      - 1100:1100
    command: ./gateway
    environment:
      STRUCTURED_LOGGING: "false"
    depends_on:
      - database
      - accounts
    links:
      - database

  accounts:
    container_name: accounts
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        project: accounts
        project_path: ./cmd
    ports:
      - 1300:1300
      - 50051:50051
    command: ./accounts
    environment:
      STRUCTURED_LOGGING: "false"
      PGUSER: user-development
      PGNAME: development
    depends_on:
      - database
    links:
      - database

  sessions:
    container_name: sessions
    restart: "no"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        project: sessions
        project_path: ./cmd
    ports:
      - 1200:1200
    command: ./sessions
    environment:
      PGUSER: user-development
      PGDATABASE: development
    depends_on:
      - database
    links:
      - database

  jaeger:
    container_name: jaeger_container
    restart: always
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

volumes:
  postgres_volume:
