@startuml myDiagram
!define LIGHTBLUE

set namespaceSeparator .

class AccountsService << (S,Aquamarine) >> {
    storage StorageInterface
}
class SessionsService << (S,Aquamarine) >> {
    storage StorageInterface
}

class handler.Handler {
}

class MacroStorage {
    database databaseInterface
}

class gin.Router {
}

class proto.AccountsClient {
}
class proto.SessionsClient {
}

AccountsService <|-- MacroStorage 
SessionsService <|-- MacroStorage 

gateway <|-- handler.Handler

handler.Handler <|-- proto.AccountsClient
handler.Handler <|-- proto.SessionsClient
handler.Handler <|-- gin.Router

MacroStorage <|-- database

database <|-- StorageInterface

@enduml
