@startuml myDiagram
!define LIGHTBLUE

set namespaceSeparator .

class gatewayService << (S,Aquamarine) >> {
}

' Microservices
class accountsService << (S,Aquamarine) >> {
    storage StorageInterface
}
class sessionsService << (S,Aquamarine) >> {
    storage StorageInterface
}

class handler.Handler {
    AuthMiddleware()
    InitializeRoutes()
    Run()
    --
    createAccount()
}

interface databaseInterface {
}

class Storage {
    database databaseInterface
}

class zap.SugaredLogger {
}

class mux.Router {
}

class proto.AccountsClient {
}
class proto.SessionsClient {
}

' Storage
class DB {
}
class sqlx.DB {
}

accountsService <|-- zap.SugaredLogger
sessionsService <|-- zap.SugaredLogger


gatewayService <|-- handler.Handler

handler.Handler <|-- zap.SugaredLogger
handler.Handler <|-- proto.AccountsClient
handler.Handler <|-- proto.SessionsClient
handler.Handler <|-- mux.Router
handler.Handler <|-- Storage

Storage <|-- databaseInterface
databaseInterface *-- DB
DB <|-- sqlx.DB

@enduml
